import pandas as pd
import numpy as np
from copy import deepcopy
from itertools import product
import sympy as sp
from Graph import *
from RandomDataMaker import *
from GainsCalculator import *


class GainsEstimator:
    """
    The goal of this class is to estimate the gains \alpha_{i|j} from an
    input file that contains a dataset. The dataset has the node names
    graph.ord_nodes as column labels, and instances of node values in each row.

    Attributes
    ----------
    alp_mat_estimate: np.array of shape=(dim, dim), where dim=number of nodes
        estimate of the alpha matrix. Contains estimates for the gains
        \alpha_{i|j}
    cov_mat: np.array of shape=(dim, dim)
        The covariance matrix calculated from the input datset
    cum_err: float
        cummulative error, equal to the sum of the absolute values of the
        errors err_i_j in gains_sb_list.
    gains_sb_list: list[sp.Equality]
        A list of equations of the form 'alp_i_L_j = float' if the graph has
        an arrow x_j->x_i, or of the form 'err_i_j = float' if that arrow is
        missing from the graph. 'err_i_j' is an error equal to the
        difference between both sides of an equation that constrains the
        covariances.


    """

    def __init__(self, graph, path, gains_calculator):
        """

        Parameters
        ----------
        graph: Graph
        path: str
            path to input file containing dataset
        gains_calculator: GainsCalculator
        """
        df = pd.read_csv(path)
        assert list(df.columns) == graph.ord_nodes
        self.cov_mat = df.cov().to_numpy()
        # print("ddfgh", df.cov())
        self.gains_sb_list = deepcopy(gains_calculator.gains_sb_list)
        assert self.gains_sb_list is not None
        dim = graph.num_nds
        self.alp_mat_estimate = np.zeros((dim, dim))
        self.cum_err = 0
        for i in range(len(self.gains_sb_list)):
            eq = self.gains_sb_list[i]
            str0 = str(eq.args[0])
            if str0[0:3] == "cov":
                str1 = "err" + str0[3:len(str0)]
                eq = sp.Eq(sp.Symbol(str1), eq.args[0]-eq.args[1])
            for row, col in product(range(dim), range(dim)):
                if row <= col:
                    cov_sb = sp.Symbol("cov_" +
                         str(row) + "_" + str(col))
                    eq = eq.subs({cov_sb: self.cov_mat[row, col]})
            self.gains_sb_list[i] = eq
            str1 = str(eq.args[1])
            if str0[0:3] == "alp":
                row_str, col_str = str0[4:len(str0)].split("_L_")
                row, col = int(row_str), int(col_str)
                self.alp_mat_estimate[row, col] = float(str1)
            else:
                self.cum_err += abs(float(str1))

    def print_gains(self, true_alp_mat=None):
        """
        This method prints the estimates of the gains \alp_{i|j} if arrow
        $x_j->x_i$ is present in the DAG, or of err_i_j if that arrow is
        absent in the DAG. It also prints, if it's available, the true
        \alp_{ i|j} next to its estimate

        Parameters
        ----------
        true_alp_mat: np.array of shape=(dim, dim)
            This input contains the true alpha matrix alp_mat, if one is
            known. One would be known if the input dataset was generated by
            RandomDataMaker.

        Returns
        -------
        None

        """
        for eq in self.gains_sb_list:
            str0 = str(eq.args[0])
            str1 = "%.6f" % float(eq.args[1])
            str01 = str0 + "= " + str1
            if str(eq.args[0])[0:3] != "alp" or true_alp_mat is None:
                print("\n", str01)
            else:
                row_str, col_str = str0[4:len(str0)].split("_L_")
                row, col = int(row_str), int(col_str)
                true = true_alp_mat[row, col]
                true_str = "%.6f" % true
                print("\n", str01, ", true=", true_str)


if __name__ == "__main__":
    def main():
        dot = "digraph G {\n" \
              "a->b;\n" \
              "a->s;\n" \
              "n->s,a,b;\n" \
              "}"
        with open("tempo13.txt", "w") as file:
            file.write(dot)
        dot_path = 'tempo13.txt'
        # dot_path = 'dot_atlas/good_bad_trols_G1.dot'
        graph = Graph(dot_path)
        dim = graph.num_nds
        sig_eps = [0.1]*dim
        dmaker = RandomDataMaker(graph, sig_eps=sig_eps)
        num_rows = 100
        data_path = "test_data.csv"
        dmaker.generate_dataset_csv(num_rows, data_path)
        calc = GainsCalculator(graph)
        calc.calculate_gains_sb()
        gest = GainsEstimator(graph, data_path, calc)
        gest.print_gains(true_alp_mat=dmaker.alp_mat)
        print("alp_mat_estimate=\n", gest.alp_mat_estimate)
        print("cum_err=", gest.cum_err)

    main()
